### ISSUE TITLE
 set [closeOnOutsideClick]="true" seems does not work

### ISSUE THREAD

**Issue by jamessawyer** [penniath/ngx-boot-modal#1]
I set the property closeOnOutsideClick true, it does not close the modal. What's more, after clicked outside place, Escape key does not work too. great library BTW.

**Comment by jamessawyer** [comment]
Sorry, I just found I forgot import the bootstrap v3 styles. Can you add postition feature, so I can place modal everywhere I like?

**Comment by penniath** [comment]
What do you want to achieve exactly with that position?
Which feature are you looking for?

**Comment by jamessawyer** [comment]
Acutally, I just want sometimes modal can show up in the center of screen , I know it's not a big deal,so don't bother any more. Can you figure out a way to dynamic create a modal using a ModalService or something else?

**Comment by penniath** [comment]
You should create your own CSS classes and apply them via modalClass input property from ModalComponent.
Currently, only in-template modal components are supported.

**Comment by jamessawyer** [comment]
Thanks for your reply, Waiting for more new features

**Comment by penniath** [comment]
Thank you for the feedback.
I'm closing this issue as it is not an actual bug.
